export const Data = [
  {
    id: 1,
    exerciseName: "Incline DB Press",
    bodyPart: "chest",
    logoImage: "/imgaes/exercise-icons/incline_db_press.png",
    exerciseImage: "/imgaes/exercise-images/incline db press.png",
  },
  {
    id: 2,
    exerciseName: "Lateral Raises",
    bodyPart: "Shoulder",
    logoImage: "/imgaes/exercise-icons/lateral_raises.png",
    exerciseImage: "/imgaes/exercise-images/lateral raises.png",
  },
  {
    id: 3,
    exerciseName: "Lat Pulldown",
    bodyPart: "Back",
    logoImage: "/imgaes/exercise-icons/lat pulldown.png",
    exerciseImage: "/imgaes/exercise-images/lat pulldown.png",
  },
  {
    id: 4,
    exerciseName: "Cable Rows",
    bodyPart: "Back",
    logoImage: "/imgaes/exercise-icons/cable rows.png",
    exerciseImage: "/imgaes/exercise-images/cable rows.png",
  },
  {
    id: 5,
    exerciseName: "Cable Flies",
    bodyPart: "chest",
    logoImage: "/imgaes/exercise-icons/cable flies.png",
    exerciseImage: "/imgaes/exercise-images/cable flies.png",
  },
  {
    id: 6,
    exerciseName: "Shoulder DB Press",
    bodyPart: "Shoulder",
    logoImage: "/imgaes/exercise-icons/shoulder press.png",
    exerciseImage: "/imgaes/exercise-images/shoulder press.png",
  },
  {
    id: 7,
    exerciseName: "Squats",
    bodyPart: "Glutes & Hamstrings",
    logoImage: "/imgaes/exercise-icons/squats.png",
    exerciseImage: "/imgaes/exercise-images/squats.png",
  },
  {
    id: 8,
    exerciseName: "Leg Extension",
    bodyPart: "Quads",
    logoImage: "/imgaes/exercise-icons/leg extension.png",
    exerciseImage: "/imgaes/exercise-images/leg extension.png",
  },
  {
    id: 9,
    exerciseName: "Tricep Pushdown",
    bodyPart: "Tricep",
    logoImage: "/imgaes/exercise-icons/tricep extension.png",
    exerciseImage: "/imgaes/exercise-images/tricep pushdown.png",
  },
  {
    id: 10,
    exerciseName: "Incline Cable Curls",
    bodyPart: "Bicep",
    logoImage: "/imgaes/exercise-icons/Incline cable curls.png",
    exerciseImage: "/imgaes/exercise-images/incline db curls.png",
  },
  {
    id: 11,
    exerciseName: "Bicep DB Curls",
    bodyPart: "Biceps",
    logoImage: "/imgaes/exercise-icons/bicep curls.png",
    exerciseImage: "/imgaes/exercise-images/bicep curls.png",
  },
  {
    id: 12,
    exerciseName: "Bench Press",
    bodyPart: "Back",
    logoImage: "/imgaes/exercise-icons/Bench press.png",
    exerciseImage: "/imgaes/exercise-images/bench press.png",
  },
];
